name: CURL Request with Secrets

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send POST request
        # Inspect requests at https://public.requestbin.com/r/enw9z3kw0afbh
        shell: bash
        run: |
          curl -H "Authorization: ${{ secrets.REQ_SECRET }}" -X POST "https://enw9z3kw0afbh.x.pipedream.net"
          
