name: CURL Request with Secrets

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set environment variable from GitHub secret
        env:
          REQ_SECRET: ${{ secrets.REQ_SECRET }}
        run: echo "REQ_SECRET=$REQ_SECRET" >> $GITHUB_ENV

      - name: Verify secret loads correctly
        run: echo "$REQ_SECRET"
    
      - name: Send POST request
        # Inspect requests at https://public.requestbin.com/r/enw9z3kw0afbh
        run: |
          curl -H "Authorization: $MY_SECRET" -X POST "https://enw9z3kw0afbh.x.pipedream.net"
          
