name: CURL Request with Secrets

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send POST request using python
        # Inspect requests at https://public.requestbin.com/r/enw9z3kw0afbh
        env:
          REQ_SECRET: ${{ secrets.REQ_SECRET }}
        run: |
          import os
          import requests
          headers = {
            'Authorization': os.getenv("REQ_SECRET")
          }
          requests.request("POST", "https://enw9z3kw0afbh.x.pipedream.net", headers=headers)
        shell: python
          
